title: Beautiful Django
name: Beautiful Django
email: brunet.adrien@gmail.com
description: Beautiful Django Book Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beautifuldjango.com" # the base hostname & protocol for your site
twitter_username: Adrien_Brunet
github_username:  beautifuldjango
gems:
  - jemoji
# Build settings
markdown: kramdown
google_analytics: UA-42192634-6
disqus:
  shortname: beautifuldjango


# Categories are:
# - general: about the whole thing
# - manifesto: about what we're trying to achieve as a whole
# - book: about the book specifically
#
